//! Request and response types for the utility RPCs.
//!
//! Transcribed from the `RPCResult` blocks of `validateaddress`
//! (`src/rpc/output_script.cpp`) and `getindexinfo` (`src/rpc/node.cpp`) in
//! Bitcoin Core v31.1. No response struct rejects unknown fields, so a newer
//! node adding a field does not break deserialization.

/// Result of `validateaddress`.
///
/// `isvalid` is the only field guaranteed present. On success the node fills
/// `address`, `script_pub_key` and the witness/script details; on failure it
/// fills `error` and `error_locations` instead.
#[derive(Debug, Clone, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct AddressValidation {
    /// If the address is valid or not.
    pub isvalid: bool,
    /// The bitcoin address validated.
    #[cfg_attr(feature = "serde", serde(default))]
    pub address: Option<String>,
    /// The hex-encoded output script generated by the address.
    #[cfg_attr(feature = "serde", serde(default, rename = "scriptPubKey"))]
    pub script_pub_key: Option<String>,
    /// If the key is a script.
    #[cfg_attr(feature = "serde", serde(default))]
    pub isscript: Option<bool>,
    /// If the address is a witness address.
    #[cfg_attr(feature = "serde", serde(default))]
    pub iswitness: Option<bool>,
    /// The version number of the witness program.
    #[cfg_attr(feature = "serde", serde(default))]
    pub witness_version: Option<u64>,
    /// The hex value of the witness program.
    #[cfg_attr(feature = "serde", serde(default))]
    pub witness_program: Option<String>,
    /// Error message, if any.
    #[cfg_attr(feature = "serde", serde(default))]
    pub error: Option<String>,
    /// Indices of likely error locations in the address, if known (e.g.
    /// Bech32 errors).
    #[cfg_attr(feature = "serde", serde(default))]
    pub error_locations: Option<Vec<u64>>,
}

/// Status of one index, held in the [`std::collections::BTreeMap`] returned
/// by `getindexinfo`, keyed by index name.
#[derive(Debug, Clone, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct IndexInfo {
    /// Whether the index is synced or not.
    pub synced: bool,
    /// The block height to which the index is synced.
    ///
    /// `IndexSummary::best_block_height` (`index/base.h:33`) is filled from
    /// `pindex->nHeight` or left at its `0` default (`index/base.cpp:478,481`),
    /// never negative.
    pub best_block_height: u64,
}
